### ISSUE TITLE
Not defended strings in struct VarInfo.

### ISSUE THREAD

**Issue by Execorn** [dainbow/Stack#1]
Hello! You have a problem with storing your strings in struct VarInfo. Strings file*, function*, name* are not safe, because only pointer to these strings are stored without any canaries or string hash's. I strongly recommend you to check, if they are safe. Moreover, you can simply check them with your GetHash function and easily check in function IsAllOk. 
By not defending these strings, your program may print out wrong information into the dump file.

**Comment by dainbow** [comment]
Ok, I'll fix it

>
